algoritmo "Contador"
var
   contador, n: inteiro
inicio
      Escreval ("-----------------------------------")
      Escreva ("Digite um numero maior que 0: ")
      leia (n)
      Escreval
      contador <- 0
      enquanto (contador <= n) faca
      Escreval (contador)
      contador <- contador + 1
      FimEnquanto
      Escreval
      Escreval ("Terminei de contar!")
      Escreval ("-----------------------------------")
fimalgoritmo